version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - SQL_SERVER_HOST=db
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd
    ports:
      - "1433:1433"
    volumes:
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
